import { PresetExpression } from './types';

// Predefined expressions with English translation mapping and ACTION instructions
export const PRESET_EXPRESSIONS: PresetExpression[] = [
  { label: '開心', value: 'Happy, smiling cheerfully, raising hands in joy, sparkles around head' },
  { label: '尷尬', value: 'Awkward, sweat drop on head, nervous smile, scratching head with hand' },
  { label: '生氣', value: 'Angry, furious, veins popping, clenched fist raised, anger symbols' },
  { label: '驚訝', value: 'Surprised, wide eyes, open mouth, hands on cheeks in shock' },
  { label: '害羞', value: 'Shy, blushing, looking away, poking fingers together (fiddling fingers)' },
  { label: '大笑', value: 'Laughing out loud, eyes closed joyfully, holding stomach with hands' },
  { label: '害怕', value: 'Scared, terrified, pale face, biting fingernails or hiding behind hands' },
  { label: '哭泣', value: 'Crying, tears streaming down, rubbing eyes with hands, puddle of tears' },
];

// Image generation model (supports image output)
export const MODEL_NAME = 'gemini-2.5-flash-preview-05-20';
// Text-only model for style list generation
export const TEXT_MODEL_NAME = 'gemini-2.5-flash';
// Multimodal model for metadata (accepts image + text)
export const METADATA_MODEL_NAME = 'gemini-2.5-flash';

export const OUTPUT_SIZE = 320;

export const SYSTEM_PROMPT = `You are an image variation model that modifies facial expression, body language, and background.

Do not change character identity, hairstyle, outfit style, art style, or lighting.
However, YOU MUST add hand gestures (arms/hands entering frame) and comic emotional symbols (hearts, sweat drops, veins, sparkles) that match the requested expression.

Change the background to a solid bright green color (Hex #00FF00, RGB 0, 255, 0).
The background must be completely flat.

Preserve line quality, materials, color palette, and rendering style.

No text overlays generated by the model (text will be added in post-processing).`;

export const getGenerationPrompt = (expression: string) => `
**Per-job User prompt**

- Task: Create a variation of the provided character image changing the facial expression to: **${expression}**.
- **Action & Symbols**: Generate matching hand gestures (e.g., heart hands for love, thumbs up, scratching head) and comic symbols (e.g., floating hearts, sweat drops, anger marks) appropriate for this expression.
- **Background Requirement**: Replace the background with a solid bright green color (Hex #00FF00, RGB 0, 255, 0). Ensure it is a flat, pure color.
- If the expression provided above is not in English, translate it to the closest English facial expression AND action description internally.
- Keep character identity, face proportions, hairstyle, and outfit style identical.
- Output: clean PNG, ${OUTPUT_SIZE}x${OUTPUT_SIZE} square, no text characters.
`;